feat: update build-containers.yml

diff --git a/.github/workflows/03-build-containers.yml b/.github/workflows/03-build-containers.yml
--- a/.github/workflows/03-build-containers.yml
+++ b/.github/workflows/03-build-containers.yml
@@ -42,13 +42,16 @@ jobs:
       - name: "Trivy Scan"
         uses: aquasecurity/trivy-action@0.31.0
         id: trivy-scan
-        with:
-          scan-type: "image"
-          image-ref: ${{ steps.build.outputs.IMAGE_NAME_FORMAT }}
-          format: "table"
-          severity: "CRITICAL,HIGH"
-          exit-code: "1"
-          output: "trivy-report.txt"
+        run: |
+          ~/.local/bin/trivy-bin/trivy image \
+            --format table \
+            --severity CRITICAL,HIGH \
+            --output trivy-report.txt \
+            ${{ steps.build.outputs.IMAGE_NAME_FORMAT }} || true
+          if grep -q "CRITICAL" trivy-report.txt; then
+            echo "::error Vulnerabilidades CRÍTICAS encontradas no scan de segurança"
+            exit 1
+          fi
         continue-on-error: true
 
       - name: "Upload do relatório de vulnerabilidades"
